---
title: "Preliminary Estimations"
author: "Lemi Daba"
date: "4/7/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Preliminaries:
```{r message=FALSE, warning=FALSE}
rm(list = ls())

# packages
library(tidyverse)
library(haven)
library(scales)
library(stargazer)
library(AER)

theme_set(theme_light())
```


Need to run data cleaning first
```{r raw_data, cache=TRUE}
source("scripts/extract_clean.R")
```

## OLS and IV on all sample

Start by estimating a simple model for both OLS and IV

First stage regression (no covariates): 
```{r chunk_1}
sfrst <- lm(IMTI ~ E_is, data = joined)
stargazer(sfrst, type = "text")
```

2SLS on the whole sample:

```{r chunk_2}
smod_ols <- lm(wage_employ ~ IMTI, data = joined)
smod_iv <- ivreg(wage_employ ~ IMTI | E_is, data = joined)
stargazer(smod_ols, smod_iv, type = "text")
```

The same regressions as above, but excluding the Addis Ababa sample:

```{r chunk_3}
sfrst_noaa <- lm(IMTI ~ E_is, data = joined, subset = region_r3 != "Addis Ababa")

smod_ols_noaa <- lm(wage_employ ~ IMTI, data = joined, subset = region_r3 != "Addis Ababa")
smod_iv_noaa <- ivreg(wage_employ ~ IMTI | E_is, data = joined, subset = region_r3 != "Addis Ababa")

stargazer(sfrst_noaa, type = "text")
stargazer(smod_ols_noaa, smod_iv_noaa, type = "text")
```



```{r}
aa_sample <- joined %>% 
  filter(region_r3 == "Addis Ababa") %>% 
  mutate(
    ethnic_D = if_else(chethnic == "Amhara", 0.75, 0),
    IMIT = if_else(chethnic == "Amhara",6, 0)
    )

ols_aa <- lm(wage_employ ~ ethnic_D, data = aa_sample)
iv_aa <- ivreg(wage_employ ~ IMTI | ethnic_D, data = aa_sample)
stargazer(ols_aa, iv_aa, type = "text")
```

```{r chunk_3}

smod_iv_test__noaa <- ivreg(perco_maths ~ IMTI | E_is, data = joined, subset = region != "Addis Ababa")

smod_iv_test_noaa <- ivreg(perco_lang ~ IMTI | E_is, data = joined, subset = region != "Addis Ababa")


stargazer(smod_iv_test__noaa, smod_iv_test_noaa, type = "text")
```


```{r chunk_3}

smod_iv_test__noaa <- ivreg(math_score ~ IMTI | E_is, data = joined, subset = region != "Addis Ababa")

smod_iv_test_noaa <- ivreg(verbal_score ~ IMTI | E_is, data = joined, subset = region != "Addis Ababa")


stargazer(smod_iv_test__noaa, smod_iv_test_noaa, type = "text")
```









