---
title: "Analyzing joined younger cohort data"
author: "Lemi Daba"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}

library(tidyverse)
library(stargazer)
library(lfe)

schsur_yl_joined <- read_csv("../data/schsur_yl_joined.csv")

schsur_yl_aa <- schsur_yl_joined %>% 
  filter(region == "Addis Ababa")

```


# Using test scores data from the school survey

```{r}

# Estimation for the AA sample

iv3aa_yc <- felm(
  formula = maths_score_w2 ~ entype_r4 + chsex + zbfa + stunting + caredu_r1 + 
    careage_r1 + hhsize + wi_new + hq_new + 
    cd_new + elecq_new + ownlandhse_r1 + factor(foodsec_r3) | 
    0 | (IMTI ~ E_is), 
  
  data = schsur_yl_aa
  )


iv4aa_yc <- felm(
  formula = literacy_score_w2 ~ entype_r4 + chsex + zbfa + stunting + caredu_r1 + 
    careage_r1 + hhsize + wi_new + hq_new + 
    cd_new + elecq_new + ownlandhse_r1 + factor(foodsec_r3) | 
    0 | (IMTI ~ E_is), 
  
  data = schsur_yl_aa
  )

```


```{r}

stargazer(
  iv3aa_yc, iv4aa_yc,
  keep = c("IMTI"),
  keep.stat = c("n","rsq"),
  type = "text"
)

stargazer(
  iv3aa_yc$stage1, iv4aa_yc$stage1, 
  keep = c("E_is"),
  keep.stat = c("n"),
  type = "text"
)


```

## using yl cognitive scores:

```{r}

iv5aa_yc <- felm(
  formula = math_score ~ entype_r4 + chsex + zbfa + stunting + caredu_r1 + 
    careage_r1 + hhsize + wi_new + hq_new + 
    cd_new + elecq_new + ownlandhse_r1 + factor(foodsec_r3) | 
    0 | (IMTI ~ E_is), 
  
  data = schsur_yl_aa
)


iv6aa_yc <- felm(
  formula = verbal_score ~ entype_r4 + chsex + zbfa + stunting + caredu_r1 + 
    careage_r1 + hhsize + wi_new + hq_new + 
    cd_new + elecq_new + ownlandhse_r1 + factor(foodsec_r3) | 
    0 | (IMTI ~ E_is), 
  
  data = schsur_yl_aa
)


stargazer(
  iv5aa_yc, iv6aa_yc,
  keep = c("IMTI"),
  keep.stat = c("n","rsq"),
  type = "text"
)

stargazer(
  iv5aa_yc$stage1, iv6aa_yc$stage1, 
  keep = c("E_is"),
  keep.stat = c("n"),
  type = "text"
)

```


