
# Date created: 2026-07-02 (reconstruction) ; revised 2026-07-02
# Author: Lemi Daba (tayelemi@gmail.com)
# DEPENDS ON: data/non_aa_samp.csv  (produced by scripts/extract_clean.R)
#
# Produces Table 3 of the manuscript, tables/table_rev.tex in the Overleaf
# project MTI__learning_and_job_outcomes.
#
# "Testing Likely Channels: Impact of MTI on Cognitive Ability".
# This is the first-stage relationship of the channels IV design: the effect of
# the interaction of the nature-assigned instrument E_is ("Predicted MTI") and
# MTI intake IMTI ("MTIuse") on cognitive ability, measured by the standardized
# language ("Verbal") score. Estimated over the whole non-Addis sample and
# excluding the Amhara region.  DV = Verbal score; single OLS coefficient shown.

library(readr)
library(dplyr)
library(lfe)

# ---- output location (pass a path as arg to override) -----------------------
args <- commandArgs(trailingOnly = TRUE)
out_file <- if (length(args) >= 1) args[[1]] else
  "MTI__learning_and_job_outcomes/tables/table_rev.tex"

# ---- data -------------------------------------------------------------------
standardize <- function(x) (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)

non_aa_samp <- read_csv("data/non_aa_samp.csv", show_col_types = FALSE) %>%
  mutate_if(is.character, as.factor) %>%
  filter(raw_lang != 0) %>%
  mutate(
    std_lang = standardize(raw_lang),   # "Verbal score" (dependent variable)
    inst     = E_is * IMTI              # "E_is * MTIuse"
  )

# ---- estimation -------------------------------------------------------------
# covariate set = estimation.R's covar1 (make_formula_iv)
covars <- paste(
  "chsex", "zbfa", "stunting", "caredu_r1", "careage_r1", "factor(caresex_r1)",
  "hhsize", "wi_new", "hq_new", "cd_new", "elecq_new", "ownlandhse_r1",
  "factor(foodsec_r3)",
  sep = " + "
)

fit_fs <- function(dat) felm(as.formula(paste0("std_lang ~ inst + ", covars)), data = dat)

# columns (1)-(2): Whole Sample, Excluding Amhara
models <- list(
  fit_fs(non_aa_samp),
  fit_fs(filter(non_aa_samp, region != "Amhara"))
)

coefs <- lapply(models, function(m) summary(m)$coefficients["inst", , drop = TRUE])
Ns    <- vapply(models, function(m) m$N, integer(1))

# ---- LaTeX formatting -------------------------------------------------------
star <- function(p) if (is.na(p)) "" else if (p < .01) "$^{***}$" else
  if (p < .05) "$^{**}$" else if (p < .1) "$^{*}$" else ""
num  <- function(x) { s <- formatC(abs(x), format = "f", digits = 3)
  if (x < 0) paste0("$-$", s) else s }
coef_cell <- function(r) paste0(num(r[["Estimate"]]), star(r[["Pr(>|t|)"]]))
se_cell   <- function(r) paste0("(", formatC(r[["Std. Error"]], format = "f", digits = 3), ")")
row_cells <- function(v) paste(v, collapse = " & ")

C_coef <- row_cells(vapply(coefs, coef_cell, ""))
C_se   <- row_cells(vapply(coefs, se_cell,   ""))
N_row  <- row_cells(as.character(Ns))

# ---- write table ------------------------------------------------------------
L <- c(
  paste0("%Tex File: ", out_file),
  paste0("% Date and time: ", format(Sys.time(), "%a, %b %d, %Y - %I:%M:%S %p")),
  "% Regenerated by scripts/table_rev.R",
  "\\begin{table}[!htbp] \\centering ",
  "  \\caption{Testing Likely Channels: Impact of MTI on Cognitive Ability} ",
  "  \\label{tab:rev} ",
  "\\begin{threeparttable}",
  "\\begin{tabular}{@{\\extracolsep{5pt}}lcc} ",
  "\\\\[-1.8ex]\\hline ",
  "\\hline \\\\[-1.8ex] ",
  " & \\multicolumn{2}{c}{\\textbf{Verbal score}} \\\\ ",
  "\\cline{2-3} ",
  "\\\\[-1.8ex]",
  " & Whole & Excluding \\\\ ",
  " & Sample & Amhara \\\\",
  "\\\\[-1.8ex] & (1) & (2)\\\\ ",
  "\\hline \\\\[-1.8ex] ",
  paste0(" $E_{is}*MTIuse$ & ", C_coef, " \\\\ "),
  paste0("  & ", C_se, " \\\\ "),
  "  & & \\\\ ",
  "\\hline \\\\[-1.8ex] ",
  paste0("Observations & ", N_row, " \\\\ "),
  "\\hline ",
  "\\hline \\\\[-1.8ex] ",
  "\\end{tabular} ",
  "\\begin{tablenotes}",
  "\\footnotesize",
  "\\item \\textit{Notes:} Covariates for all regressions include sex of child, BMI-for-age z-score, dummy for stunting, parents' (caregivers') characteristics (education, age, and sex), household size, wealth, housing-quality and consumer-durables indices, access to electricity, household land ownership, and food security.  ",
  "",
  "\\item Standard errors are in parentheses. *** Significant at 1\\%, ** Significant at 5\\%, * Significant at 10\\%.",
  "\\end{tablenotes}",
  "\\end{threeparttable}",
  "\\end{table} "
)

writeLines(L, out_file)

# ---- console summary (verification) -----------------------------------------
cat("Wrote:", out_file, "\n\n")
lab <- c("Whole Sample", "Excluding Amhara")
for (i in seq_along(models)) cat(sprintf(
  "%-18s N=%3d | Verbal score ~ E_is*MTIuse = %s%s  (%s)\n",
  lab[i], Ns[i], num(coefs[[i]][["Estimate"]]), star(coefs[[i]][["Pr(>|t|)"]]),
  formatC(coefs[[i]][["Std. Error"]], format = "f", digits = 3)
))
